In [1]:
#pipinstall instaloader

In [2]:
import instaloader
import time
import numpy as np
import pandas as pd

In [3]:
# #create an instance
# # Use parameters to save diffrent metadata; chose to omit videos
# dl = instaloader.Instaloader(download_videos=False, save_metadata=False)

# # Optionally, login or load session
# # test.login('USER', 'PASSWORD')        # (static login)
# dl.interactive_login('micaket906')

## 2. List of top fashion influencers in Singapore

List of top 100 Singapore fashion influencers (by follower count), that has fashion content in their instagram. Some of these influencers might also discuss other topics like food, pets etc, which are not closely related to fashion and we might want to omit them. Additionally, we will focus on female influencers for this project. There are also a few accounts that seem to be tagged wrongly either to the topic, or the location, and I will be manually removing them. ([*source*](https://starngage.com/app/global/influencer/ranking/singapore/fashion))

In [4]:
# Load list of insta accounts
insta_acc = pd.read_csv('../data/instagram_handles.csv')

In [5]:
insta_acc.head()

,name,handle,topics,follower_count,to_exclude_pets_food
0,Jamie Chua 蔡欣颖,ec24m,Photography Travel Fashion Design Celebrities,1200000,0
1,Diya Vj,diya_menon_official,Modeling Fashion Photography,600900,0
2,Jeanette Aw 欧萱,jeanetteaw,Food Fashion Lifestyle,413300,1
3,胡佳琪 Jayley Woo,jiaqiwoo,Fashion Styling Lifestyle,409700,0
4,Rebecca Lim 林慧玲,limrebecca,Actors Fashion Art Modeling,408400,0

In [6]:
insta_acc.shape

(100, 5)

In [7]:
#keep only influencers that do not post about pets or food, as explained in markdown cell above

insta_acc = insta_acc.loc[insta_acc['to_exclude_pets_food'] == 0]
insta_acc.shape

(76, 5)

In [8]:
#remaining accounts after excluding pets and food related accounts
accounts = insta_acc['handle'].tolist()
accounts

['ec24m',
 'diya_menon_official',
 'jiaqiwoo',
 'limrebecca',
 'taufikbatisah',
 'speishi',
 'gourmetartistry',
 'dreachong',
 'carriewst',
 'kimlimhl',
 'novitalam',
 'julietan_cxq',
 'mongabong',
 'aureliang_',
 'xplacidacidx',
 'melissackoh',
 'katherinaolivia',
 'nicolekittykatx',
 'sylsylnoc',
 'elegantstylesfashion',
 'zoetay10',
 'xubin_',
 'hayleywoojiayi',
 'yahuiyh',
 'denisesoongeelyn',
 'rchlwngxx',
 'saffronsharpe',
 'euniceannabel',
 'katepang311',
 'honglingg_',
 'norfasarie',
 'elaineruimin',
 'trishachatterjee09',
 'mirchelley',
 'sleepy.tofu',
 'sheila_sim',
 'shanepowxp',
 'milapanpinij',
 'fionafussi',
 'cheyennechesney',
 'soniachew',
 'narellekheng',
 'ohhowstrange',
 'andeecys',
 'garimpandodicas',
 'xoxoapo',
 'jacelyn_tay',
 'xinlinnn',
 'kym_ng',
 'sophiachong',
 'alluradesign',
 'theeditorsmarket',
 'jeanettewn',
 'graceyuki',
 'ms_rach',
 'martinapagani',
 'anna_en',
 'theclosetlover',
 'jamiepang',
 'mingbridges',
 'charlottelum',
 'polkadope',
 'aimeechengbradshaw',
 'pxdkitty',
 'esh_wari',
 'tippytapp',
 'berlin.ng',
 'dj.shinigami',
 'prisceliachan',
 'slavagee',
 'trumpster.d',
 'gnitil',
 'symoneoei',
 'felixgerlach',
 's_f_y_96',
 'celestechen']

In [9]:
#manually identify some that do not seem to be tagged correctly to fashion or to Singapore
#also remove blogshops since they are our target clients who want to predict color trends, so we shouldn't use their own colors

wrong_tag = ['gourmetartistry','diya_menon_official','martinapagani','katherinaolivia','sylsylnoc','elegantstylesfashion','norfasarie','trishachatterjee09','sleepy.tofu','milapanpinij',
 'garimpandodicas','kym_ng','sophiachong','alluradesign','jeanettewn']
blogshops = ['theeditorsmarket','theclosetlover']
male = ['taufikbatisah','xubin_','felixgerlach','shanepowxp','andeecys']
to_remove = wrong_tag + blogshops + male
to_remove

['gourmetartistry',
 'diya_menon_official',
 'martinapagani',
 'katherinaolivia',
 'sylsylnoc',
 'elegantstylesfashion',
 'norfasarie',
 'trishachatterjee09',
 'sleepy.tofu',
 'milapanpinij',
 'garimpandodicas',
 'kym_ng',
 'sophiachong',
 'alluradesign',
 'jeanettewn',
 'theeditorsmarket',
 'theclosetlover',
 'taufikbatisah',
 'xubin_',
 'felixgerlach',
 'shanepowxp',
 'andeecys']

In [10]:
# final list of accounts
for acc in to_remove:
    if acc in accounts:
        accounts.remove(acc)

In [11]:
len(accounts)

54

In [12]:
#for loop to go through all target accounts cannot work
#download_profile downloads ALL posts from each account and limit is easily hit when we do a for loop
#also did not succeed at building a timed loop, hence will have to manualy download
#and manually stop the request when all 2021 posts are downloaded


# #timedloop
# seconds = 60
# for acc in accounts:
#     start_time = time.time()
#     while True:
#         current_time = time.time()
#         elapsed_time = current_time - start_time
#         while not elapsed_time > seconds:
#             current_time = time.time()
#             elapsed_time = current_time - start_time
#             dl.download_profile(acc)

In [13]:
#the following code from instaloader documentation to extract posts by date also did not work
# from datetime import datetime
# from itertools import dropwhile, takewhile

# import instaloader

# L = instaloader.Instaloader()

# posts = instaloader.Profile.from_username(L.context, "soulshiok").get_posts()

# SINCE = datetime(2021, 1, 1)
# UNTIL = datetime(2021, 11, 1)

# for post in takewhile(lambda p: p.date > UNTIL, dropwhile(lambda p: p.date > SINCE, posts)):
#     print(post.date)
#     L.download_post(post, '#soulshiok')

In [14]:
#due to the manual nature of extraction, will limit to top 34 accounts
top_accounts = accounts[:34]
top_accounts

['ec24m',
 'jiaqiwoo',
 'limrebecca',
 'speishi',
 'dreachong',
 'carriewst',
 'kimlimhl',
 'novitalam',
 'julietan_cxq',
 'mongabong',
 'aureliang_',
 'xplacidacidx',
 'melissackoh',
 'nicolekittykatx',
 'zoetay10',
 'hayleywoojiayi',
 'yahuiyh',
 'denisesoongeelyn',
 'rchlwngxx',
 'saffronsharpe',
 'euniceannabel',
 'katepang311',
 'honglingg_',
 'elaineruimin',
 'mirchelley',
 'sheila_sim',
 'fionafussi',
 'cheyennechesney',
 'soniachew',
 'narellekheng',
 'ohhowstrange',
 'xoxoapo',
 'jacelyn_tay',
 'xinlinnn']

In [15]:
final_acct_df = pd.DataFrame(top_accounts, columns = ['handle'])
final_acct_df

              handle
0              ec24m
1           jiaqiwoo
2         limrebecca
3            speishi
4          dreachong
5          carriewst
6           kimlimhl
7          novitalam
8       julietan_cxq
9          mongabong
10        aureliang_
11      xplacidacidx
12       melissackoh
13   nicolekittykatx
14          zoetay10
15    hayleywoojiayi
16           yahuiyh
17  denisesoongeelyn
18         rchlwngxx
19     saffronsharpe
20     euniceannabel
21       katepang311
22        honglingg_
23      elaineruimin
24        mirchelley
25        sheila_sim
26        fionafussi
27   cheyennechesney
28         soniachew
29      narellekheng
30      ohhowstrange
31           xoxoapo
32       jacelyn_tay
33          xinlinnn

In [16]:
final_acct_df = final_acct_df.merge(insta_acc, how='left', on='handle')
final_acct_df.drop(columns='to_exclude_pets_food')

,handle,name,topics,follower_count
0,ec24m,Jamie Chua 蔡欣颖,Photography Travel Fashion Design Celebrities,1200000
1,jiaqiwoo,胡佳琪 Jayley Woo,Fashion Styling Lifestyle,409700
2,limrebecca,Rebecca Lim 林慧玲,Actors Fashion Art Modeling,408400
3,speishi,SOH PEI SHI 苏培诗,Fashion Lifestyle Beauty,346800
4,dreachong,Andrea Chong,Fashion Styling Lifestyle,305500
5,carriewst,Carrie Wong 黄思恬,Fashion Modeling Lifestyle,297400
6,kimlimhl,K I M L I M,Fashion Lifestyle Design Technology Celebritie...,288200
7,novitalam,Novita Lam,Fashion,286300
8,julietan_cxq,Julie Tan 陈欣淇,Actors Modeling Fashion,283100
9,mongabong,Mongchin Yeoh,Art Beauty Fashion,281200
10,aureliang_,"Hi, I’m Aurelia 🕊",Fashion Lifestyle Modeling,275100
11,xplacidacidx,-fiona xie- *KITTY PONG*,Fashion Modeling Art,268800
12,melissackoh,Melissa Celestine Koh,Fashion Lifestyle Architecture Hair & Beauty,267800
13,nicolekittykatx,Nicole Low,Art Fashion Modeling,240300
14,zoetay10,Zoe Tay鄭惠玉,Fashion Modeling,223900
15,hayleywoojiayi,Hayley Woo 胡佳嬑,Modeling Fashion Art,210300
16,yahuiyh,Ya Hui 雅慧,Actors Modeling Fashion Music,204900
17,denisesoongeelyn,Denise Soong Ee Lyn 🍉,Fashion,204500
18,rchlwngxx,✘ Rachel Wong 誼恩 ✘,Fashion Modeling Lifestyle Photography Travel ...,196500
19,saffronsharpe,Saffron Sharpe,Fashion Lifestyle Modeling Design Hair & Beaut...,190600
20,euniceannabel,EUNICE ANNABEL LIM,Modeling Fashion Architecture Travel Photograp...,187800
21,katepang311,龎蕾馨 Kate Pang,Moms Modeling Fashion,187100
22,honglingg_,Hong Ling,Actors Modeling Fashion Fitness Nature & Outdo...,173700
23,elaineruimin,Elaine Rui Min,Travel Fashion Photography,165900
24,mirchelley,MICHELLE 🐾,Fashion Art Lifestyle,161000
25,sheila_sim,Sheila Sim 沈琳宸,Art Modeling Fashion,153400
26,fionafussi,FIONA FUSSI 智欣,Fashion Beauty Lifestyle,141100
27,cheyennechesney,cheyenne,Modeling Fashion,140700
28,soniachew,SONIA,Fashion Lifestyle,140500
29,narellekheng,Narelle,Actors Fashion Lifestyle,138200
30,ohhowstrange,Kimberly Haley Wang,Fashion Lifestyle Modeling,136800
31,xoxoapo,apple cty 陳芷尤,Modeling Fashion,134100
32,jacelyn_tay,郑秀珍 | Wellness | Beauty,Fashion Lifestyle Coaching,133200
33,xinlinnn,XinLin Khaw,Fashion Lifestyle,129800

In [18]:
#export final 34 accounts and information to csv
final_acct_df.to_csv('../data/final_acct_df.csv', index = False)

In [17]:
#run code below to download for each individual account
# dl.download_profile('xinlinnn')