In [1]:
import pandas as pd
from pathlib import Path
import re
import datetime
import numpy as np
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
from sklearn.metrics import pairwise_distances
from PIL import Image
from PIL import ImageFile
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
#set instance of dataframe using rgba_0.csv
rgba = pd.read_csv('../data/rgba/rgba_0.csv')
rgba = rgba.T
image_list = list(rgba.index)
rgba_array = rgba.to_numpy()

rgba_df = pd.DataFrame(zip(image_list, rgba_array), columns = ['image_list', 'rgba_list'])
rgba_df

,image_list,rgba_list
0,../pictures/wo_background/ec24m/ec24m_2021-01-...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
1,../pictures/wo_background/ec24m/ec24m_2021-11-...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
2,../pictures/wo_background/ec24m/ec24m_2021-03-...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
3,../pictures/wo_background/ec24m/ec24m_2021-06-...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
4,../pictures/wo_background/ec24m/ec24m_2021-02-...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
...,...,...
195,../pictures/wo_background/ec24m/ec24m_2021-12-...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
196,../pictures/wo_background/ec24m/ec24m_2021-11-...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
197,../pictures/wo_background/ec24m/ec24m_2021-08-...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
198,../pictures/wo_background/ec24m/ec24m_2021-09-...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
199,../pictures/wo_background/ec24m/ec24m_2021-08-...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."

In [3]:
%%time

for n in range(34):
    rgba = pd.read_csv('../data/rgba/rgba_'+str(n)+'.csv')
    rgba = rgba.T
    image_path = list(rgba.index)
    rgba_array = rgba.to_numpy()
    df = pd.DataFrame(zip(image_path, rgba_array), columns = ['image_list', 'rgba_list'])
    rgba_df = pd.concat([rgba_df,df])

CPU times: user 29.8 s, sys: 4.9 s, total: 34.7 s
Wall time: 35.9 s

In [4]:
rgba_df.reset_index(drop=True, inplace = True)
rgba_df

,image_list,rgba_list
0,../pictures/wo_background/ec24m/ec24m_2021-01-...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
1,../pictures/wo_background/ec24m/ec24m_2021-11-...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
2,../pictures/wo_background/ec24m/ec24m_2021-03-...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
3,../pictures/wo_background/ec24m/ec24m_2021-06-...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
4,../pictures/wo_background/ec24m/ec24m_2021-02-...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
...,...,...
6834,../pictures/wo_background/xinlinnn/xinlinnn_20...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
6835,../pictures/wo_background/xinlinnn/xinlinnn_20...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
6836,../pictures/wo_background/xinlinnn/xinlinnn_20...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
6837,../pictures/wo_background/xinlinnn/xinlinnn_20...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
6838,../pictures/wo_background/xinlinnn/xinlinnn_20...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."

In [5]:
image_list = rgba_df['image_list']
instagram_handle = []
date_post = []
seq_post_samedate = []

for image in image_list:
    handle = re.search('wo_background/(.*)/', image).group(1)
    instagram_handle.append(handle)
    date_post.append(image[-16:-6])
    seq_post_samedate.append(image[-5:-4])

In [6]:
rgba_df['instagram_handle'] = instagram_handle
rgba_df['date_post'] = date_post
rgba_df['seq_post_samedate'] = seq_post_samedate

In [7]:
#delete corrupted posts that contains .DS
rgba_df = rgba_df[~rgba_df.date_post.str.contains('.DS')]
rgba_df.shape

(6837, 5)

In [8]:
rgba_df['seq_post_samedate'] = rgba_df['seq_post_samedate']\
.map({'C':'0','c':'0','0':'10','1':'1','2':'2','3':'3','4':'4','5':'5','6':'6','7':'7','8':'8','9':'9'})
rgba_df['seq_post_samedate'].value_counts()

<ipython-input-8-706bc5aae8c8>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rgba_df['seq_post_samedate'] = rgba_df['seq_post_samedate']\

1     1933
0     1805
2     1680
3      777
4      320
5      125
6       78
7       43
8       34
9       30
10      12
Name: seq_post_samedate, dtype: int64

In [9]:
rgba_df['date_post'] = pd.to_datetime(rgba_df['date_post'])
rgba_df['seq_post_samedate'] = rgba_df['seq_post_samedate'].astype(str).astype(int)

<ipython-input-9-8bfad6c914ef>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rgba_df['date_post'] = pd.to_datetime(rgba_df['date_post'])
<ipython-input-9-8bfad6c914ef>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rgba_df['seq_post_samedate'] = rgba_df['seq_post_samedate'].astype(str).astype(int)

In [10]:
#extract month
def month_extract(x):
    month = x.month
    return month

In [11]:
rgba_df['month'] = rgba_df['date_post'].apply(month_extract)
rgba_df

<ipython-input-11-8aca52a00c05>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rgba_df['month'] = rgba_df['date_post'].apply(month_extract)

,image_list,rgba_list,instagram_handle,date_post,seq_post_samedate,month
0,../pictures/wo_background/ec24m/ec24m_2021-01-...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",ec24m,2021-01-31,0,1
1,../pictures/wo_background/ec24m/ec24m_2021-11-...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",ec24m,2021-11-09,2,11
2,../pictures/wo_background/ec24m/ec24m_2021-03-...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",ec24m,2021-03-03,0,3
3,../pictures/wo_background/ec24m/ec24m_2021-06-...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",ec24m,2021-06-29,1,6
4,../pictures/wo_background/ec24m/ec24m_2021-02-...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",ec24m,2021-02-03,0,2
...,...,...,...,...,...,...
6834,../pictures/wo_background/xinlinnn/xinlinnn_20...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",xinlinnn,2021-01-15,4,1
6835,../pictures/wo_background/xinlinnn/xinlinnn_20...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",xinlinnn,2021-03-03,0,3
6836,../pictures/wo_background/xinlinnn/xinlinnn_20...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",xinlinnn,2021-02-03,0,2
6837,../pictures/wo_background/xinlinnn/xinlinnn_20...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",xinlinnn,2021-08-18,0,8
6838,../pictures/wo_background/xinlinnn/xinlinnn_20...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",xinlinnn,2021-01-31,0,1